services:
  - type: web
    name: solarpal-backend
    runtime: python3
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: ALLOWED_ORIGINS
        value: "http://localhost:3000,https://your-frontend-domain.vercel.app,https://your-frontend-domain.netlify.app"
    # Optional: Custom domains
    # domains:
    #   - solarpal-api.yourdomain.com